### ISSUE TITLE
Issue with the chrome extension. 

### ISSUE THREAD

**Issue by iDominusU** [Gskartwii/Rbx_CustomFont#3]
As of recently, Google added CORB to Google Chrome. CORB prevents the browser from delivering certain cross-origin network responses to a web page. This means that a chrome extension is sometimes unable to pull product data from ROBLOX's API. Even after solving this issue, the response seems to be blank. In the script.js file, it seems to get hung up and errors around line 18-20. After looking into it, the response is completely blank even after manually changing the asset ID variable.

Edit: I have fixed the extension with some minor edits. Still a bit buggy as ROBLOX doesn't allow too many requests to their API within a short period, returning an error prompting you to wait before trying again - but still functional.

**Comment by Gskartwii** [comment]
Unfortunately, I'm no longer maintaining this project. I've now updated the README to reflect this. Please check #5.

**Comment by jmkd3v** [comment]
> Edit: I have fixed the extension with some minor edits. Still a bit buggy as ROBLOX doesn't allow too many requests to their API within a short period, returning an error prompting you to wait before trying again - but still functional.

Can you send this version of the extension over?

**Comment by TheRBXDEVV** [comment]
Did the generator worked for you ? i still dont understand why doesnt it works. Do you have any idea abt this ? @iDominusU  @jmkd3v
